import { 
  SHOP, 
  ABOUT_TITLE, 
  ABOUT_CAPTION, 
  CONTACT_TITLE, 
  ABOUT_TEXT, 
  CONTACT_ADDRESS_CAPTION, 
  ADDRESS, 
  OPEN_HOURS, 
  MAP_CAPTION ,
  SHIPPING_TITLE, 
  DELIVERY_CAPTION, 
  PAYMENT_CAPTION, 
  EXCHANGE_CAPTION, 
  DELIVERY, 
  PAYMENT, 
  EXCHANGE, 
  COPYRIGHT, 
  REGISTER,
  NAV, 
  PRODUCTS_NAV_NAME, 
  PRODUCTS_NAV_FIRST_NAME, 
  FOOTER_NAV, 
  S3_ALBUM_NAME, 
  AWS_BUCKET_NAME,
  AWS_REGION,
  CART_KEY, 
  BRAND,
  MAP_IMG,
  SHIPPING_IMG,
  ABOUT_IMG,
  CONTACT_IMG,
  CAROUSEL_IMG_ARR,
  LOGO,
  BRAND_WIDTH,
  BRAND_LEFT,
  BRAND_MARGIN_LEFT,
  BRAND_TOP
} from "./charm";

export { 
  SHOP, 
  ABOUT_TITLE, 
  ABOUT_CAPTION, 
  CONTACT_TITLE, 
  ABOUT_TEXT, 
  CONTACT_ADDRESS_CAPTION, 
  ADDRESS, 
  OPEN_HOURS, 
  MAP_CAPTION ,
  SHIPPING_TITLE, 
  DELIVERY_CAPTION, 
  PAYMENT_CAPTION, 
  EXCHANGE_CAPTION, 
  DELIVERY, 
  PAYMENT, 
  EXCHANGE, 
  COPYRIGHT, 
  REGISTER,
  NAV, 
  PRODUCTS_NAV_NAME, 
  PRODUCTS_NAV_FIRST_NAME, 
  FOOTER_NAV, 
  S3_ALBUM_NAME, 
  AWS_BUCKET_NAME,
  AWS_REGION,
  CART_KEY, 
  BRAND,
  MAP_IMG,
  SHIPPING_IMG,
  ABOUT_IMG,
  CONTACT_IMG,
  CAROUSEL_IMG_ARR,
  LOGO,
  BRAND_WIDTH,
  BRAND_LEFT,
  BRAND_MARGIN_LEFT,
  BRAND_TOP
}


export const CAROUSEL_INTERVAL = 10000;

export const CAROUSEL_INIT_STATE = 0;
export const ICON_LIST = [
  { icon: "cm-font-heart", url: ""},
  { icon: "cm-font-facebook", url: ""},
  { icon: "cm-font-x-twitter", url: ""},
  { icon: "cm-font-pinterest", url: ""}
]
export const CART_CLOSED_POSITION = "-410px";
export const CART_OPENED_POSITION = "0px";

